### ISSUE TITLE
Renderização do Artigo 2 pós Revisão

### ISSUE THREAD

**Issue by JeffGM** [DCC831-Aprendizado-Descritivo/2024.1#15]
Gostaríamos de pedir aos Publicitários que regerem o Artigo 2 depois que o Pull Request de revisão (https://github.com/DCC831-Aprendizado-Descritivo/2024.1/pull/14) for mergeado, pois também tivemos problemas para gerá-lo localmente. 

Obrigado,

**Comment by rvimieiro** [comment]
Gerou normalmente no repositório. Vou fechar a issue, mas, se vocês detectarem algum problema, eu reabro.
