### ISSUE TITLE
Execução de código Jupyter Artigo2

### ISSUE THREAD

**Issue by rvimieiro** [DCC831-Aprendizado-Descritivo/2024.1#8]
A página do artigo 2 não pode ser criada pelo pipeline do Github devido aos requisitos para a execução do código. Existem duas alternativas para que o grupo resolva essa pendência:
1. Renderizar localmente a página, forçando a execução na máquina local e depois subindo os arquivos necessários criados pelo Quarto local;
2. Ajustar o arquivo de configuração para que os requisitos possam ser instalados corretamente e a página criada no servidor.

A descrição completa das soluções podem ser vistas em https://quarto.org/docs/publishing/github-pages.html#github-action.

Um esboço da segunda está prevista no arquivo de configuração atual, porém ainda não funcional.

**Comment by hfscheid** [comment]
Boa tarde Professor, gostaria de entender melhor como subir os arquivos já renderizados. Devemos subir o diretório `_site` inteiro? Ou apenas o `seminario1/artigo2.ipynb` ?

**Comment by rvimieiro** [comment]
Pelo que está descrito na documentação, quando você rodar o `quarto render`, ele deve produzir um diretório _freeze com o resultado da execução. Parece que isso já é suficiente para ele conseguir compilar o restante do site. Veja se essa tentativa resolve. Depois testamos outras alternativas, se for o caso.
Pode fazer o commit e subir a nova versão. Não precisa fazer pull request. Vocês têm acesso direto ao repositório.

**Comment by hfscheid** [comment]
Perfeito, funcionou. Subi na branch `artigo2`
